---
title: "(scapes)Classifications"
author: "Gerald H. Taranto"
date: "`r format(Sys.time(), '%a %d, %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{(scapes)Classifications}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.width = "100%", echo = TRUE, out.width="600px", fig.align='center', message=FALSE, warning=FALSE)
```

## Raster classifications

`scapesClassification` is a package designed to perform raster classifications: 

> Identify discrete geographic objects and segments of space over a raster surface; each space or object is identified by a unique class or set of classes. 


## Design principles

The design of `scapesClassification` was guided by a few principles that can be resumed in the following points:

* Raster surfaces generally present some distinctive attribute(s), easy to identify and classify; 

* Distinctive attributes can be used to map an initial set of raster cells to a class. These cells are hereafter referred to as _anchor cells_;

* Then, raster cells can be classified not only considering their intrinsic attributes, but also their spatial relationships with anchor cells (see _class contiguity_ and _class continuity_ in [rule evaluation](scapesClassification_01_2_RuleEvaluation.html)); 

* Every time a raster portion is classified, it can be considered as a new anchor location for the following classification steps. 


## Classification rules

Geo-spaces are classified using sets of user-defined classification rules presented in the form of [conditional statements](https://en.wikipedia.org/wiki/Conditional_(computer_programming) "Wikipedia definition"). Classification rules evaluate either to true or false and determine, at each classification step, what raster cells are mapped to a class.  

As explained in the section [format inputs](scapesClassification_01_1_FormatInputs.html#attribute-table), (scapes)Classifications start by converting single and multi-layer raster objects into attribute tables. Each column of the attribute table represents a variable and contains the values of a raster layer. Classification rules can be built accessing by name all the variables stored in the attribute table. For instance, if our attribute table has two columns named `"slope"` and `"height"` we could build the following classification rule: `"slope > 5 & height > 1000"`. 

Rules are passed to a scapesClassification function as a single **`character string`**. They consist of combination of arithmetic (`+|-|*|/|^|%%|%/%`), relational (`>|<|>=|<=|==|!=|%/%`) and logic operators (`&||`), base R functions (e.g., `abs(variable_name)`), variables names (i.e., `names(attTbl)`) and previous classifications (referred to and stored as `"classVector"`) (see `?conditions`). 


## Types of classification rules

**Absolute, test cell condition.**


**Absolute, test cell neighborhood condition.**


**Relative, focal cell condition.**


**Relative, test cell neighborhood condition.**







